# SEO Research — SEO Factors Research Tool
# Copyright (C) 2026 Andrew Philip Weilbacher
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Commercial licensing: contact@marketingprowess.simplelogin.com — see COMMERCIAL.md
model_list:

  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  master_key: "sk-awwgBwU35nuKfxXx3MgXC1L-vUY31N-ySdhkbQNlff8"

environment_variables:
  OPENAI_API_KEY: "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"
